### ISSUE TITLE
Link to AmazonS3.zip in README.md not pointing right

### ISSUE THREAD

**Issue by lfalvarez** [Daniel-KM/Omeka-S-module-AmazonS3#2]
Hey! I believe that where it says: "Download the last release AmazonS3.zip from the list of releases" the link is pointing somewhere that requires login in gitlab.
If I'm not mistaken the link should point simply to https://github.com/Daniel-KM/Omeka-S-module-AmazonS3/archive/master.zip

**Comment by XGhozt** [comment]
The link works for me, maybe it's been fixed.

**Comment by lfalvarez** [comment]
ohhh its weird, this is what I get:

![amazon-omeka](https://user-images.githubusercontent.com/585757/92001610-e4aaa300-ed0c-11ea-9a49-4754d946d460.gif)

**Comment by Daniel-KM** [comment]
Thanks for the info.
The link was fixed on gitlab, but not on github, so it was strange. The link is good now: https://gitlab.com/Daniel-KM/Omeka-S-module-AmazonS3/-/releases (unlike github, there is a "/-/")
